- settings:
  transport:
    path_type: Linear             # option: ["Linear", "GVP", "VP"]
    prediction: velocity          # option: ["velocity", "score", "noise"]
    loss_weight: velocity         # option: [None, "velocity", "likelihood"]
    sample_eps: 0.1
    train-eps: 0.2

  ode:
    atol: 1e-6
    rtol: 1e-3
    reverse: false
    likelihood: false

  sde:
    sampling-method: Euler        # option: ["Euler", "Heun"]
    diffusion-form: sigma         # option: ["constant", "SBDM", "sigma", "linear", "decreasing", "increasing-decreasing"]
    diffusion-norm: 1.0
    last-step: Mean               # option: [None, "Mean", "Tweedie", "Euler"]
    last-step-size: 0.04

  infer:
      resolution: "1024x1024"              # option: ["1024x1024", "512x2048", "2048x512", "(Extrapolation) 1664x1664", "(Extrapolation) 1024x2048", "(Extrapolation) 2048x1024"]
      num_sampling_steps: 60      # range: 1-1000
      cfg_scale: 4.               # range: 1-20
      solver: "euler"             # option: ["euler", "dopri5", "dopri8"]
      t_shift: 4                  # range: 1-20 (int only)
      ntk_scaling: true
      proportional_attn: true
      seed: 0